const teamData=[{name:'Founder / Creative Director',role:'Profile image and name editable in admin'},{name:'Head of Production',role:'Profile image and name editable in admin'},{name:'Customer Experience Lead',role:'Profile image and name editable in admin'}];
function renderTeam(){document.getElementById('team').innerHTML=teamData.map((p,i)=>`<article class="person"><div class="photo">Department head photo ${i+1}<br><small>Replace from admin</small></div><div class="meta"><h4>${p.name}</h4><span>${p.role}</span></div></article>`).join('')}
function openBespoke(type){document.getElementById('bespokeModal').classList.add('open'); if(type)document.getElementById('bType').value=type}
function closeBespoke(){document.getElementById('bespokeModal').classList.remove('open')}
function submitBespoke(){const n=document.getElementById('bName').value||'Customer';const p=document.getElementById('bPhone').value||'Not supplied';const t=document.getElementById('bType').value;const m=document.getElementById('bMeasure').value;const o=document.getElementById('bOccasion').value||'Not supplied';const notes=document.getElementById('bNotes').value||'None';const msg=`Hello OVOSKG, I want to start a bespoke order.%0A%0AName: ${encodeURIComponent(n)}%0APhone: ${encodeURIComponent(p)}%0AType: ${encodeURIComponent(t)}%0AMeasurements: ${encodeURIComponent(m)}%0AOccasion/deadline: ${encodeURIComponent(o)}%0ANotes: ${encodeURIComponent(notes)}`;window.open('https://wa.me/2347070489393?text='+msg,'_blank')}
function trackOrder(){const id=document.getElementById('orderId').value.trim().toUpperCase();const p=document.getElementById('progress');const stages=['Confirmed','Measurements','Cutting','Sewing','Finishing','Ready'];if(id==='OVS-DEMO-001'){document.getElementById('trackTitle').textContent='OVS-DEMO-001 · Finishing';document.getElementById('trackNote').textContent='Preview order only. Your garment is in finishing and quality checks.';document.getElementById('trackline').innerHTML=stages.map((x,i)=>`<div class="stage ${i<5?'done':''}">${x}</div>`).join('');p.classList.add('show')}else{document.getElementById('trackTitle').textContent='Order not found in preview';document.getElementById('trackNote').textContent='The live version will search OVOSKG’s order database. Try OVS-DEMO-001 for the prototype.';document.getElementById('trackline').innerHTML='';p.classList.add('show')}}
function saveMeasurements(){const notice=document.getElementById('measurementNotice');notice.textContent='Measurement profile saved on this device for the prototype. Production version will securely attach measurements to the customer account.';localStorage.setItem('ovoskg_measurement_profile','saved')}
renderTeam();
document.getElementById('bespokeModal').addEventListener('click',e=>{if(e.target.id==='bespokeModal')closeBespoke()});
